plot-all:
	@../plot_.py --file-name pdc/vid0r0 pdc/vid0j pdc/vid1 pdc/vid1j pdc/vid2 pdc/vid2j

plot-0:
	@../plot_.py --file-name pdc/vid0r0 pdc/vid0j

plot-1:
	@../plot_.py --file-name pdc/vid1 pdc/vid1j

plot-2:
	@../plot_.py --file-name pdc/vid2 pdc/vid2j

plot-r:
	@../plot_.py --file-name pdc/vid0r0 pdc/vid0r50 pdc/vid0r150 pdc/vid0r250 pdc/vid0j
